version: '2'

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - '5000:5000'
  mongo:
    image: mongo
    container_name: mongo-prod
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
