version: '3'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - ./logs:/logs
    ports:
      - '3000:3000'
    expose:
      - 3000
    links:
      - "db:database"
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
    expose: 
      - 27017
