version: '3'

services:
  db:
    image: mongo
    restart: always
    networks:
      - dev-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  dev-network:
    driver: bridge
